# Generated by Django 4.2.29 on 2026-04-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_id', models.CharField(max_length=100, unique=True, verbose_name='缺陷编号')),
                ('title', models.CharField(max_length=200, verbose_name='缺陷标题')),
                ('description', models.TextField(verbose_name='缺陷描述')),
                ('severity', models.CharField(choices=[('blocker', '阻断'), ('critical', '严重'), ('major', '主要'), ('minor', '次要'), ('trivial', '轻微')], default='major', max_length=50, verbose_name='严重程度')),
                ('status', models.CharField(choices=[('open', '待处理'), ('in_progress', '处理中'), ('resolved', '已解决'), ('closed', '已关闭'), ('rejected', '已拒绝')], default='open', max_length=50, verbose_name='状态')),
                ('env', models.CharField(blank=True, choices=[('t', 'T环境'), ('pre', 'Pre环境'), ('prod', '线上环境')], max_length=20, null=True, verbose_name='发现环境')),
                ('type', models.CharField(choices=[('online', '线上缺陷'), ('function', '功能缺陷'), ('requirement', '需求缺陷'), ('design', '设计缺陷'), ('ux', '用户体验'), ('suggestion', '建议')], default='function', max_length=50, verbose_name='缺陷类型')),
                ('group', models.CharField(blank=True, max_length=100, null=True, verbose_name='归属团队')),
                ('source', models.CharField(choices=[('test', '测试发现'), ('tech', '技术发现'), ('business', '业务反馈'), ('user', '用户反馈')], default='test', max_length=50, verbose_name='缺陷来源')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '缺陷',
                'verbose_name_plural': '缺陷',
                'ordering': ['-created_at'],
            },
        ),
    ]
