# Generated by Django 4.2.29 on 2026-04-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='tapd_bug_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='TAPD Bug ID'),
        ),
    ]
