# Generated by Django 4.2.29 on 2026-04-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0003_bug_tapd_bug_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='bug_id',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='缺陷编号'),
        ),
    ]
