# Generated by Django 4.2.29 on 2026-04-17 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iterations', '0003_iteration_source_iteration_source_created_at_and_more'),
        ('bugs', '0004_alter_bug_bug_id'),
    ]

    operations = [
        # severity → priority（保留已有数据）
        migrations.RenameField(
            model_name='bug',
            old_name='severity',
            new_name='priority',
        ),
        migrations.AlterField(
            model_name='bug',
            name='priority',
            field=models.CharField(choices=[('blocker', '阻断'), ('critical', '严重'), ('major', '主要'), ('minor', '次要'), ('trivial', '轻微')], default='major', max_length=50, verbose_name='优先级'),
        ),
        # 新增字段
        migrations.AddField(
            model_name='bug',
            name='iteration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bugs', to='iterations.iteration', verbose_name='所属迭代'),
        ),
        migrations.AddField(
            model_name='bug',
            name='source_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='来源平台创建时间'),
        ),
        migrations.AddField(
            model_name='bug',
            name='source_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='来源平台更新时间'),
        ),
    ]
