# Generated by Django 4.2.29 on 2026-04-17 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugs', '0005_rename_severity_to_priority_and_add_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='tapd_bug_id',
        ),
        migrations.AddField(
            model_name='bug',
            name='browser',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='浏览器'),
        ),
        migrations.AddField(
            model_name='bug',
            name='bug_category',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='缺陷分类'),
        ),
        migrations.AddField(
            model_name='bug',
            name='bug_source',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='缺陷根源'),
        ),
        migrations.AddField(
            model_name='bug',
            name='cc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='抄送人'),
        ),
        migrations.AddField(
            model_name='bug',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='关闭时间'),
        ),
        migrations.AddField(
            model_name='bug',
            name='creator',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='bug',
            name='current_owner',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='当前处理人'),
        ),
        migrations.AddField(
            model_name='bug',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, verbose_name='自定义字段'),
        ),
        migrations.AddField(
            model_name='bug',
            name='de',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='开发人员'),
        ),
        migrations.AddField(
            model_name='bug',
            name='effort',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='预估工时'),
        ),
        migrations.AddField(
            model_name='bug',
            name='effort_completed',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='完成工时'),
        ),
        migrations.AddField(
            model_name='bug',
            name='effort_exceed',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='超出工时'),
        ),
        migrations.AddField(
            model_name='bug',
            name='effort_remain',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='剩余工时'),
        ),
        migrations.AddField(
            model_name='bug',
            name='fixer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='修复人'),
        ),
        migrations.AddField(
            model_name='bug',
            name='flows',
            field=models.TextField(blank=True, null=True, verbose_name='流转记录'),
        ),
        migrations.AddField(
            model_name='bug',
            name='in_progress_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始处理时间'),
        ),
        migrations.AddField(
            model_name='bug',
            name='label',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='bug',
            name='module',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='模块'),
        ),
        migrations.AddField(
            model_name='bug',
            name='origin_phase',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='发现阶段'),
        ),
        migrations.AddField(
            model_name='bug',
            name='os',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='操作系统'),
        ),
        migrations.AddField(
            model_name='bug',
            name='platform',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='软件平台'),
        ),
        migrations.AddField(
            model_name='bug',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='拒绝时间'),
        ),
        migrations.AddField(
            model_name='bug',
            name='release_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='发布计划ID'),
        ),
        migrations.AddField(
            model_name='bug',
            name='resolution',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='解决方法'),
        ),
        migrations.AddField(
            model_name='bug',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='解决时间'),
        ),
        migrations.AddField(
            model_name='bug',
            name='severity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='严重程度'),
        ),
        migrations.AddField(
            model_name='bug',
            name='source_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='来源平台ID'),
        ),
        migrations.AddField(
            model_name='bug',
            name='te',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='测试人员'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_bugs', to=settings.AUTH_USER_MODEL, verbose_name='报告人'),
        ),
    ]
