# Generated by Django 4.2.29 on 2026-04-20 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0006_remove_bug_tapd_bug_id_bug_browser_bug_bug_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('open', '待处理'), ('in_progress', '处理中'), ('resolved', '已解决'), ('done', '已完成'), ('closed', '已关闭'), ('rejected', '已拒绝'), ('suspended', '挂起')], default='open', max_length=50, verbose_name='状态'),
        ),
    ]
