# Generated by Django 4.2.29 on 2026-04-20 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_module_created_by_ai_module_git_code_path_and_more'),
        ('bugs', '0007_alter_bug_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='module_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='模块名称'),
        ),
        migrations.AddField(
            model_name='bug',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bugs', to='projects.project', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bugs', to='projects.module', verbose_name='关联模块'),
        ),
    ]
