# Generated by Django 4.2.29 on 2026-04-09 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.AddField(
            model_name='project',
            name='tech_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tech_lead_projects', to=settings.AUTH_USER_MODEL, verbose_name='技术负责人'),
        ),
        migrations.AddField(
            model_name='project',
            name='test_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_lead_projects', to=settings.AUTH_USER_MODEL, verbose_name='测试负责人'),
        ),
    ]
