# Generated by Django 4.2.29 on 2026-04-15 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0012_aiunderstanding_ai_quality_issues_and_more'),
        ('projects', '0003_remove_status_add_tech_test_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='created_by_ai',
            field=models.BooleanField(default=False, verbose_name='由AI创建'),
        ),
        migrations.AddField(
            model_name='module',
            name='git_code_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Git代码路径'),
        ),
        migrations.AddField(
            model_name='module',
            name='git_repo_url',
            field=models.URLField(blank=True, null=True, verbose_name='Git仓库URL'),
        ),
        migrations.AddField(
            model_name='module',
            name='status',
            field=models.CharField(choices=[('active', '正式'), ('draft', '草稿')], default='active', max_length=20, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='ModuleKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_type', models.CharField(choices=[('pattern', '技术模式'), ('convention', '约定规范'), ('dependency', '依赖关系'), ('risk', '已知风险'), ('decision', '技术决策')], max_length=20, verbose_name='知识类型')),
                ('content', models.TextField(verbose_name='知识内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_entries', to='projects.module', verbose_name='所属模块')),
                ('source_requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_knowledge', to='requirements.requirement', verbose_name='来源需求')),
            ],
            options={
                'verbose_name': '模块知识',
                'verbose_name_plural': '模块知识',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequirementRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('related', '相关'), ('depends_on', '依赖'), ('conflicts', '冲突'), ('extends', '扩展'), ('replaces', '替代')], max_length=20, verbose_name='关系类型')),
                ('confidence', models.FloatField(default=1.0, verbose_name='置信度（0-1）')),
                ('created_by_ai', models.BooleanField(default=False, verbose_name='由AI创建')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('from_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='requirements.requirement', verbose_name='来源需求')),
                ('to_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='requirements.requirement', verbose_name='目标需求')),
            ],
            options={
                'verbose_name': '需求关联',
                'verbose_name_plural': '需求关联',
                'ordering': ['-created_at'],
                'unique_together': {('from_requirement', 'to_requirement', 'relation_type')},
            },
        ),
    ]
