# Generated by Django 4.2.29 on 2026-04-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_module_created_by_ai_module_git_code_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='项目实现逻辑说明'),
        ),
    ]
