# Generated by Django 4.2.29 on 2026-04-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iterations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteration',
            name='source',
            field=models.CharField(choices=[('sys', '本系统创建'), ('tapd', 'TAPD'), ('jira', 'Jira')], default='sys', max_length=50, verbose_name='来源'),
        ),
        migrations.AddField(
            model_name='iteration',
            name='source_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='来源平台创建时间'),
        ),
        migrations.AddField(
            model_name='iteration',
            name='source_id',
            field=models.CharField(blank=True, help_text='TAPD Iteration ID / Jira Sprint ID 等', max_length=200, null=True, verbose_name='来源平台ID'),
        ),
        migrations.AddField(
            model_name='iteration',
            name='source_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='来源平台更新时间'),
        ),
        migrations.AlterUniqueTogether(
            name='iteration',
            unique_together={('source', 'source_id')},
        ),
    ]
