# Generated by Django 4.2.29 on 2026-04-20 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_module_created_by_ai_module_git_code_path_and_more'),
        ('users', '0005_team_parent'),
        ('iterations', '0003_iteration_source_iteration_source_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteration',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iterations', to='users.team', verbose_name='所属团队'),
        ),
        migrations.AlterField(
            model_name='iteration',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iterations', to='projects.project', verbose_name='所属项目'),
        ),
    ]
