# Generated by Django 4.2.29 on 2026-04-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_team_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('product_manager', '产品经理'), ('developer', '开发人员'), ('tester', '测试人员'), ('project_manager', '项目经理'), ('product_tl', '产品TL'), ('developer_tl', '开发TL'), ('tester_tl', '测试TL'), ('admin', '管理员'), ('super_admin', '超级管理员')], default='developer', max_length=50, verbose_name='角色'),
        ),
    ]
