# Generated by Django 4.2.29 on 2026-04-09 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='中文姓名'),
        ),
        migrations.AddField(
            model_name='user',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL, verbose_name='直属上级'),
        ),
        migrations.AddField(
            model_name='user',
            name='qw_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='企微中文名'),
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='users.team', verbose_name='所属团队'),
        ),
    ]
