# Generated by Django 4.2.29 on 2026-04-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(max_length=50, verbose_name='目标类型')),
                ('target_id', models.BigIntegerField(verbose_name='目标ID')),
                ('field', models.CharField(max_length=100, verbose_name='变更字段')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='旧值')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='新值')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='变更时间')),
            ],
            options={
                'verbose_name': '变更记录',
                'verbose_name_plural': '变更记录',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_id', models.CharField(max_length=100, unique=True, verbose_name='需求编号')),
                ('name', models.CharField(max_length=200, verbose_name='需求名称')),
                ('status', models.CharField(choices=[('pending_review', '待评审'), ('pending_tech_review', '待技评'), ('pending_development', '待开发'), ('in_development', '开发中'), ('pending_test', '待测试'), ('in_testing', '测试中'), ('pending_acceptance', '待验收'), ('pending_release', '待上线'), ('pending_regression', '待回归'), ('completed', '已完成'), ('closed', '关闭')], default='pending_review', max_length=50, verbose_name='状态')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('urgent', '紧急')], default='medium', max_length=50, verbose_name='优先级')),
                ('description', models.TextField(blank=True, null=True, verbose_name='详细描述')),
                ('requirement_md', models.TextField(blank=True, null=True, verbose_name='需求MD')),
                ('technical_md', models.TextField(blank=True, null=True, verbose_name='技术MD')),
                ('figma_url', models.URLField(blank=True, null=True, verbose_name='Figma链接')),
                ('gitlab_branch', models.JSONField(blank=True, default=list, verbose_name='GitLab分支')),
                ('commit_id', models.JSONField(blank=True, default=list, verbose_name='Commit ID')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('developer', models.JSONField(blank=True, default=list, verbose_name='开发人员')),
                ('tester', models.JSONField(blank=True, default=list, verbose_name='测试人员')),
                ('tech_review_time', models.DateTimeField(blank=True, null=True, verbose_name='技评时间')),
                ('test_submit_time', models.DateTimeField(blank=True, null=True, verbose_name='提测时间')),
                ('online_time', models.DateTimeField(blank=True, null=True, verbose_name='上线时间')),
                ('actual_test_submit', models.DateTimeField(blank=True, null=True, verbose_name='实际提测时间')),
                ('actual_online', models.DateTimeField(blank=True, null=True, verbose_name='实际上线时间')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='是否阻塞')),
                ('block_reason', models.TextField(blank=True, null=True, verbose_name='阻塞原因')),
                ('is_archived', models.BooleanField(default=False, verbose_name='是否归档')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '需求',
                'verbose_name_plural': '需求',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='子需求名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='详细描述')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('in_progress', '进行中'), ('completed', '已完成')], default='pending', max_length=50, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '子需求',
                'verbose_name_plural': '子需求',
            },
        ),
    ]
