# Generated by Django 4.2.29 on 2026-04-08 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
        ('iterations', '0002_initial'),
        ('requirements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subrequirement',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sub_requirements', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='subrequirement',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_requirements', to='requirements.requirement', verbose_name='所属需求'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_requirements', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='dev_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dev_owned_requirements', to=settings.AUTH_USER_MODEL, verbose_name='开发负责人'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='iteration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='iterations.iteration', verbose_name='所属迭代'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='projects.module', verbose_name='关联模块'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='requirements.requirement', verbose_name='父需求'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='product_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_requirements', to=settings.AUTH_USER_MODEL, verbose_name='产品人员'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='projects.project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='test_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_owned_requirements', to=settings.AUTH_USER_MODEL, verbose_name='测试负责人'),
        ),
        migrations.AddField(
            model_name='changelog',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to=settings.AUTH_USER_MODEL, verbose_name='变更人'),
        ),
        migrations.AddIndex(
            model_name='changelog',
            index=models.Index(fields=['target_type', 'target_id'], name='requirement_target__54496b_idx'),
        ),
    ]
