# Generated by Django 4.2.29 on 2026-04-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='req_type',
            field=models.CharField(choices=[('product', '产品需求'), ('technical', '技术需求'), ('ui', 'UI设计')], default='product', max_length=50, verbose_name='需求类型'),
        ),
    ]
