# Generated by Django 4.2.29 on 2026-04-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0003_requirement_req_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='story_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='TAPD Story ID'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='req_type',
            field=models.CharField(choices=[('product', '产品需求'), ('technical', '技术需求'), ('ui', 'UI设计'), ('task', '任务')], default='product', max_length=50, verbose_name='需求类型'),
        ),
    ]
