# Generated by Django 4.2.29 on 2026-04-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0005_rename_fields_and_add_ai_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='ui_design_web',
            field=models.URLField(blank=True, null=True, verbose_name='UI设计稿Web链接'),
        ),
    ]
