# Generated by Django 4.2.29 on 2026-04-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0006_fix_ui_design_web_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinputasset',
            name='source_type',
            field=models.CharField(choices=[('url_fetch', '链接'), ('upload_file', '文件'), ('ai_conversation', 'AI对话')], default='upload_file', max_length=20, verbose_name='来源类型'),
        ),
        migrations.AlterField(
            model_name='aiunderstanding',
            name='source_type',
            field=models.CharField(choices=[('url_fetch', '链接'), ('upload_file', '文件'), ('ai_conversation', 'AI对话')], max_length=20, verbose_name='来源类型'),
        ),
        migrations.AlterField(
            model_name='aiunderstanding',
            name='status',
            field=models.CharField(choices=[('pending', '待生成'), ('processing', '生成中'), ('done', '已生成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
