# Generated by Django 4.2.29 on 2026-04-13 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0007_add_source_type_to_input_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiinputasset',
            name='understand_type',
            field=models.CharField(choices=[('req_md', '需求理解'), ('ui_design', 'UI设计稿'), ('ui_design_web', 'UI设计稿-Web'), ('ui_design_app', 'UI设计稿-App'), ('tech_md', '技术方案')], max_length=20, verbose_name='理解类型'),
        ),
        migrations.AlterField(
            model_name='aiunderstanding',
            name='understand_type',
            field=models.CharField(choices=[('req_md', '需求理解'), ('ui_design', 'UI设计稿'), ('ui_design_web', 'UI设计稿-Web'), ('ui_design_app', 'UI设计稿-App'), ('tech_md', '技术方案')], max_length=20, verbose_name='理解类型'),
        ),
    ]
