# Generated by Django 4.2.29 on 2026-04-14 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0008_alter_aiinputasset_understand_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='source',
            field=models.CharField(choices=[('sys', '本系统创建'), ('tapd', 'TAPD'), ('jira', 'Jira')], default='sys', max_length=50, verbose_name='来源'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='source_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='来源平台创建时间'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='source_id',
            field=models.CharField(blank=True, help_text='TAPD Story ID / Jira Issue Key 等', max_length=200, null=True, verbose_name='来源平台ID'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='source_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='来源平台更新时间'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='requirements.requirement', verbose_name='父需求'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='req_type',
            field=models.CharField(choices=[('product', '产品需求'), ('technical', '技术需求'), ('ui', 'UI设计'), ('task', '任务'), ('bug', '缺陷')], default='product', max_length=50, verbose_name='需求类型'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='story_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='TAPD Story ID (已废弃，使用source_id)'),
        ),
        migrations.AlterUniqueTogether(
            name='requirement',
            unique_together={('source', 'source_id')},
        ),
    ]
