# Generated by Django 4.2.29 on 2026-04-14 09:12

from django.db import migrations


def migrate_story_id_to_source_id(apps, schema_editor):
    """将现有 story_id 数据迁移到 source_id，并设置 source='tapd'"""
    Requirement = apps.get_model('requirements', 'Requirement')

    # 查找所有有 story_id 的需求
    requirements_with_story_id = Requirement.objects.filter(story_id__isnull=False).exclude(story_id='')

    count = 0
    for req in requirements_with_story_id:
        req.source = 'tapd'
        req.source_id = req.story_id
        req.save(update_fields=['source', 'source_id'])
        count += 1

    print(f'已迁移 {count} 条需求的 story_id 到 source_id')


def reverse_migration(apps, schema_editor):
    """回滚操作：将 source_id 恢复到 story_id"""
    Requirement = apps.get_model('requirements', 'Requirement')

    requirements_with_source_id = Requirement.objects.filter(source='tapd', source_id__isnull=False)

    for req in requirements_with_source_id:
        req.source = 'sys'
        req.source_id = None
        req.save(update_fields=['source', 'source_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0009_requirement_source_requirement_source_created_at_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_story_id_to_source_id, reverse_migration),
    ]
