# Generated by Django 4.2.29 on 2026-04-14 09:14

from django.db import migrations


def migrate_subrequirement_to_requirement(apps, schema_editor):
    """将 SubRequirement 数据迁移到 Requirement，设置 parent 字段"""
    SubRequirement = apps.get_model('requirements', 'SubRequirement')
    Requirement = apps.get_model('requirements', 'Requirement')

    subrequirements = SubRequirement.objects.all()
    count = 0

    for subreq in subrequirements:
        # 生成子需求的 requirement_id
        parent_req_id = subreq.requirement.requirement_id
        sub_req_id = f"{parent_req_id}-SUB-{subreq.id}"

        # 创建新的 Requirement 记录
        Requirement.objects.create(
            requirement_id=sub_req_id,
            name=subreq.name,
            description=subreq.description or '',
            parent=subreq.requirement,
            project=subreq.requirement.project,
            iteration=subreq.requirement.iteration,
            status=subreq.status,
            priority='medium',
            req_type='product',  # 默认为产品需求，可根据父需求类型调整
            source='sys',
            created_by=subreq.assignee if subreq.assignee else subreq.requirement.created_by,
            created_at=subreq.created_at,
            updated_at=subreq.updated_at,
        )
        count += 1

    print(f'已迁移 {count} 条子需求到 Requirement 表')


def reverse_migration(apps, schema_editor):
    """回滚操作：删除迁移的子需求"""
    Requirement = apps.get_model('requirements', 'Requirement')

    # 删除所有有 parent 的需求（迁移过来的子需求）
    Requirement.objects.filter(parent__isnull=False).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0010_migrate_story_id_to_source_id'),
    ]

    operations = [
        migrations.RunPython(migrate_subrequirement_to_requirement, reverse_migration),
    ]
