# Generated by Django 4.2.29 on 2026-04-15 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requirements', '0011_migrate_subrequirement_to_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiunderstanding',
            name='ai_quality_issues',
            field=models.JSONField(blank=True, default=list, verbose_name='AI质量问题'),
        ),
        migrations.AddField(
            model_name='aiunderstanding',
            name='ai_reviewed',
            field=models.BooleanField(default=False, verbose_name='AI理解已审核'),
        ),
        migrations.AddField(
            model_name='aiunderstanding',
            name='ai_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='AI理解审核时间'),
        ),
        migrations.AddField(
            model_name='aiunderstanding',
            name='ai_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_reviewed_understandings', to=settings.AUTH_USER_MODEL, verbose_name='AI理解审核人'),
        ),
        migrations.AddField(
            model_name='aiunderstanding',
            name='ai_understanding_result',
            field=models.JSONField(blank=True, null=True, verbose_name='AI理解结构化结果'),
        ),
        migrations.AddField(
            model_name='aiunderstanding',
            name='parse_error_msg',
            field=models.TextField(blank=True, null=True, verbose_name='解析失败原因'),
        ),
        migrations.AddField(
            model_name='aiunderstanding',
            name='parse_reviewed',
            field=models.BooleanField(default=False, verbose_name='解析已审核'),
        ),
        migrations.AddField(
            model_name='aiunderstanding',
            name='parse_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='解析审核时间'),
        ),
        migrations.AddField(
            model_name='aiunderstanding',
            name='parse_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parse_reviewed_understandings', to=settings.AUTH_USER_MODEL, verbose_name='解析审核人'),
        ),
        migrations.AddField(
            model_name='aiunderstanding',
            name='parse_status',
            field=models.CharField(choices=[('pending', '待解析'), ('processing', '解析中'), ('done', '已解析'), ('failed', '解析失败')], default='pending', max_length=20, verbose_name='解析状态'),
        ),
        migrations.AddField(
            model_name='aiunderstanding',
            name='parsed_content',
            field=models.TextField(blank=True, null=True, verbose_name='解析内容（文本+表格）'),
        ),
        migrations.AddField(
            model_name='aiunderstanding',
            name='parsed_content_with_images',
            field=models.TextField(blank=True, null=True, verbose_name='解析内容（含图片识别）'),
        ),
    ]
