# Generated by Django 4.2.29 on 2026-04-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0014_aiinputasset_is_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiinputasset',
            name='source_type',
            field=models.CharField(choices=[('url_fetch', '链接'), ('upload_file', '文件'), ('ai_conversation', 'AI对话'), ('figma_rest', 'Figma REST API'), ('figma_mcp', 'Figma MCP')], default='upload_file', max_length=20, verbose_name='来源类型'),
        ),
        migrations.AlterField(
            model_name='aiinputasset',
            name='text_content',
            field=models.TextField(blank=True, null=True, verbose_name='原始文本内容（含[图片N]占位符）'),
        ),
        migrations.AlterField(
            model_name='aiunderstanding',
            name='raw_content',
            field=models.TextField(blank=True, null=True, verbose_name='原始提取内容（已废弃）'),
        ),
        migrations.AlterField(
            model_name='aiunderstanding',
            name='source_ref',
            field=models.TextField(blank=True, null=True, verbose_name='来源描述（已废弃）'),
        ),
        migrations.AlterField(
            model_name='aiunderstanding',
            name='source_type',
            field=models.CharField(choices=[('url_fetch', '链接'), ('upload_file', '文件'), ('ai_conversation', 'AI对话'), ('figma_rest', 'Figma REST API'), ('figma_mcp', 'Figma MCP')], max_length=20, verbose_name='来源类型（已废弃）'),
        ),
    ]
