# Generated by Django 4.2.29 on 2026-04-17 02:26

from django.db import migrations, models


def migrate_figma_source_types(apps, schema_editor):
    """将 figma_rest/figma_mcp 记录统一为 url_fetch"""
    AiInputAsset = apps.get_model('requirements', 'AiInputAsset')
    AiUnderstanding = apps.get_model('requirements', 'AiUnderstanding')

    AiInputAsset.objects.filter(source_type__in=['figma_rest', 'figma_mcp']).update(source_type='url_fetch')
    AiUnderstanding.objects.filter(source_type__in=['figma_rest', 'figma_mcp']).update(source_type='url_fetch')


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0015_alter_aiinputasset_source_type_and_more'),
    ]

    operations = [
        # Data migration first: convert existing figma_rest/figma_mcp to url_fetch
        migrations.RunPython(migrate_figma_source_types, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='aiinputasset',
            name='source_type',
            field=models.CharField(choices=[('url_fetch', '链接'), ('upload_file', '文件'), ('ai_conversation', 'AI对话')], default='upload_file', max_length=20, verbose_name='来源类型'),
        ),
        migrations.AlterField(
            model_name='aiunderstanding',
            name='source_type',
            field=models.CharField(choices=[('url_fetch', '链接'), ('upload_file', '文件'), ('ai_conversation', 'AI对话')], max_length=20, verbose_name='来源类型（已废弃）'),
        ),
    ]
