# Generated by Django 4.2.29 on 2026-04-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0016_remove_figma_source_types'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='requirement',
            unique_together={('source', 'req_type', 'source_id')},
        ),
        migrations.AddField(
            model_name='requirement',
            name='category_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='需求分类ID'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='creator',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, verbose_name='自定义字段'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='developer_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='开发人员名'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='effort',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='预估工时'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='effort_completed',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='完成工时'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='effort_remain',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='剩余工时'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='label',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='module_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='模块'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='owner',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='处理人'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='plan_begin',
            field=models.DateField(blank=True, null=True, verbose_name='预计开始'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='plan_due',
            field=models.DateField(blank=True, null=True, verbose_name='预计结束'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='progress',
            field=models.IntegerField(blank=True, null=True, verbose_name='进度'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='release_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='发布计划ID'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='source_category',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='需求来源分类'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='source_children_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='来源平台子需求ID'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='source_parent_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='来源平台父需求ID'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='source_type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='来源平台类型'),
        ),
    ]
