# Generated by Django 4.2.29 on 2026-04-20 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0017_alter_requirement_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='status',
            field=models.CharField(choices=[('pending_review', '待评审'), ('pending_tech_review', '待技评'), ('pending_development', '待开发'), ('in_development', '开发中'), ('resolved', '已修复'), ('pending_test', '待测试'), ('in_testing', '测试中'), ('pending_acceptance', '待验收'), ('pending_release', '待上线'), ('pending_regression', '待回归'), ('completed', '已完成'), ('rejected', '已拒绝'), ('suspended', '挂起'), ('closed', '关闭')], default='pending_review', max_length=50, verbose_name='状态'),
        ),
    ]
