# Generated by Django 4.2.29 on 2026-04-20 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_module_created_by_ai_module_git_code_path_and_more'),
        ('requirements', '0018_alter_requirement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='projects.project', verbose_name='所属项目'),
        ),
    ]
