# Generated by Django 4.2.29 on 2026-04-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0019_alter_requirement_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='tester_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='测试人员名'),
        ),
    ]
