# Generated by Django 4.2.29 on 2026-04-21 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0020_add_tester_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='story_id',
        ),
    ]
