# Generated by Django 4.2.29 on 2026-04-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_summary'),
        ('requirements', '0021_remove_story_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiunderstanding',
            name='suggested_modules',
            field=models.JSONField(blank=True, default=list, verbose_name='AI建议模块'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='multi_requirements', to='projects.module', verbose_name='关联模块（多）'),
        ),
        migrations.AlterField(
            model_name='aiinputasset',
            name='source_type',
            field=models.CharField(choices=[('url_fetch', '链接'), ('upload_file', '文件'), ('ai_conversation', 'AI对话'), ('screenshot_input', '截图输入')], default='upload_file', max_length=20, verbose_name='来源类型'),
        ),
    ]
