# Generated by Django 4.2.29 on 2026-04-27 06:49

from django.db import migrations


def migrate_module_to_modules(apps, schema_editor):
    Requirement = apps.get_model('requirements', 'Requirement')
    for req in Requirement.objects.filter(module__isnull=False):
        req.modules.add(req.module)


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0022_aiunderstanding_suggested_modules_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_module_to_modules, migrations.RunPython.noop),
    ]
