"""
Django settings for aim project.

Generated by 'django-admin startproject' using Django 4.2.29.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bvn6e%1&1@fv)s2zdkvow$ypbi%o3p((%3o40i0c7&6(u-#o$t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.users',
    'apps.projects',
    'apps.iterations',
    'apps.requirements',
    'apps.tests',
    'apps.bugs',
    'apps.integrations',
    'apps.tasks',
    'django_celery_results',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'aim.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aim.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'm_platform',
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}

# CORS settings
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Media files (user uploads)
MEDIA_ROOT = BASE_DIR / 'static' / 'uploads'
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'users.User'

# DRF settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M:%S',  # 统一输出上海时区时间（由 TIME_ZONE=Asia/Shanghai 控制）
}

# JWT settings
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# ─── Celery 配置 ───
CELERY_BROKER_URL = 'amqp://guest:guest@localhost:5672//'
CELERY_RESULT_BACKEND = 'django-db'
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_ALWAYS_EAGER = False



# ───────────────────── 第三方集成配置 ─────────────────────
# DeepSeek AI API Key (可选，配置后启用真实 AI 功能)
DEEPSEEK_API_KEY = ''

##──────Claude API 配置 (可选，DeepSeek 不可用时降级使用)──────
# 方式1：多配置列表（优先使用）
# 配置多个 Claude API 端点，系统会按顺序尝试，直到成功
import json as _json
ANTHROPIC_CONFIGS = _json.loads(os.environ.get('ANTHROPIC_CONFIGS', '[]'))
# 方式2：单一配置（向后兼容）
CLAUDE_API_KEY = ''
ANTHROPIC_BASE_URL = ''  # 留空则使用默认 https://api.anthropic.com
ANTHROPIC_AUTH_TOKEN = ''  # 留空则使用 CLAUDE_API_KEY

# ─── AI 配置 ───
# AI 理解生成轮询超时（秒），前端超过此时间未完成则提示超时
AI_GENERATION_TIMEOUT = 180

# ─── 需求 AI 理解配置 ───
AI_UNDERSTANDING_CONFIG = {
    # 解析阶段：是否在解析时对图片进行 Vision LLM 识别
    'enable_image_recognition': True,
    # AI 理解阶段：使用哪个内容字段（parsed_content 或 parsed_content_with_images）
    'use_content_field': 'parsed_content_with_images',
    # AI 理解阶段：是否在理解时再次处理图片（通常 False，图片已在解析时处理）
    'process_images_in_understanding': False,
    # 下游代理配置
    'downstream_agents': {
        'tech_design': {
            'enabled': True,
            'auto_trigger': False,
            'include_module_knowledge': True,
            'include_related_requirements': True,
        },
        'test_generation': {
            'enabled': True,
            'auto_trigger': False,
            'min_importance': '重要',  # 只处理核心/重要功能
        },
        'defect_prediction': {
            'enabled': False,
        },
    },
}

# ─── Confluence 配置 ───
CONFLUENCE_BASE_URL = 'https://confluence.gaodunwangxiao.com/confluence'       # 例如 https://confluence.gaodunwangxiao.com
CONFLUENCE_USERNAME = os.environ.get('CONFLUENCE_USERNAME', '')
CONFLUENCE_PASSWORD = os.environ.get('CONFLUENCE_PASSWORD', '')

# ─── Figma 配置 ───
# Figma Personal Access Token，获取方式：Figma 右上角头像 → Settings → Personal access tokens
FIGMA_API_TOKEN = os.environ.get('FIGMA_API_TOKEN', '')
FIGMA_TOKEN_EXPIRES_AT = '2026-07-01'  # Token 过期日期，格式：'YYYY-MM-DD'，例如：'2026-07-01'
# Figma 对接模式：'rest'（REST API，数据持久化）| 'mcp'（MCP 实时读取）| 'rest_mcp'（REST 拉取 + MCP 处理）
FIGMA_FETCH_MODE = 'rest_mcp'

# ─── TAPD 配置 ───
# 支持三种认证方式，优先级：PAT > Basic Auth > OAuth 2.0

# 方式1：个人访问令牌 Personal Access Token (PAT) - 推荐
# 使用方式：请求头 Authorization: Bearer {token}
TAPD_PAT = os.environ.get('TAPD_PAT', '')
TAPD_WORKSPACE_ID = '43056143'  # 工作区ID，抓包看到-直接使用工作区ID-而不获取项目(否则需要company_id)

# 方式2：Basic Auth - 备用方案
# 使用方式：HTTP Basic Auth (username:api_token)
TAPD_USERNAME = ''  # TAPD 登录账号（邮箱或手机号）
TAPD_API_TOKEN = ''  # 旧版 API Token（非 PAT）
TAPD_COMPANY_ID = ''  # 获取项目接口需要用到，公司ID，在 TAPD 地址栏中查看，如 https://www.tapd.cn/company/{company_id}/

# 方式3：OAuth 2.0 - 需申请TAPD开放平台应用
TAPD_APP_ID = ''
TAPD_APP_SECRET = ''


# ─── 文件上传配置 ───
# 开关：True 上传至 OSS，False 保存到本地 MEDIA_ROOT
FILE_UPLOAD_TO_OSS = False
OSS_UPLOAD_URL = 'https://t-mgateway.gaodunwangxiao.com/mfilesvc/upload'

# 企业微信 Webhook 配置
QW_WEBHOOK_URL = os.environ.get('QW_WEBHOOK_URL', '')  # 企微机器人 Webhook 地址

# 企业微信应用配置（SSO + 消息推送）
QW_CORP_ID = ''
QW_AGENT_ID = ''
QW_SECRET = ''

# ─── 日志配置 ───
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] [{levelname}] {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'ai_service.vision': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'apps.tasks': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

