# Generated by Django 4.2.29 on 2026-04-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitLabConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_token', models.CharField(max_length=100, verbose_name='GitLab私有令牌')),
                ('api_url', models.URLField(default='https://gitlab.com/api/v4/', verbose_name='GitLab API地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'GitLab配置',
                'verbose_name_plural': 'GitLab配置',
            },
        ),
        migrations.CreateModel(
            name='TAPDConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=100, verbose_name='TAPD应用ID')),
                ('app_secret', models.CharField(max_length=100, verbose_name='TAPD应用密钥')),
                ('access_token', models.CharField(blank=True, max_length=200, null=True, verbose_name='访问令牌')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='令牌过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'TAPD配置',
                'verbose_name_plural': 'TAPD配置',
            },
        ),
    ]
