# Generated by Django 4.2.29 on 2026-04-08 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGitLabConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_url', models.URLField(verbose_name='仓库地址')),
                ('access_token', models.CharField(max_length=200, verbose_name='Access Token')),
                ('api_url', models.URLField(default='https://gitlab.com/api/v4/', verbose_name='GitLab API地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_gitlab_configs', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gitlab_config', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目GitLab配置',
                'verbose_name_plural': '项目GitLab配置',
            },
        ),
    ]
