# Generated by Django 4.2.29 on 2026-04-14 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_projectgitlabconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='tapdconfig',
            name='api_token',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='API Token'),
        ),
        migrations.AddField(
            model_name='tapdconfig',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='TAPD账号'),
        ),
        migrations.AlterField(
            model_name='tapdconfig',
            name='app_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='TAPD应用ID'),
        ),
        migrations.AlterField(
            model_name='tapdconfig',
            name='app_secret',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='TAPD应用密钥'),
        ),
    ]
