# Generated by Django 4.2.29 on 2026-04-14 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_tapdconfig_api_token_tapdconfig_username_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TAPDConfig',
        ),
    ]
