# Generated by Django 4.2.29 on 2026-04-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=100, unique=True, verbose_name='用例编号')),
                ('title', models.CharField(max_length=200, verbose_name='用例标题')),
                ('steps', models.TextField(verbose_name='测试步骤')),
                ('expected_result', models.TextField(verbose_name='预期结果')),
                ('api_test', models.TextField(blank=True, null=True, verbose_name='关联接口自动化')),
                ('ui_test', models.TextField(blank=True, null=True, verbose_name='关联UI自动化')),
                ('plat', models.CharField(choices=[('web', 'Web'), ('ios', 'iOS'), ('android', 'Android'), ('harmonyos', '鸿蒙'), ('server', '后端Server')], default='web', max_length=20, verbose_name='平台')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('passed', '通过'), ('failed', '失败'), ('blocked', '阻塞'), ('skipped', '跳过')], default='draft', max_length=50, verbose_name='状态')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('source', models.CharField(choices=[('manual', '新建'), ('import', '导入'), ('ai', 'AI生成')], default='manual', max_length=20, verbose_name='来源')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('reviewed', models.CharField(choices=[('pending', '待审核'), ('approved', '通过'), ('rejected', '不通过')], default='pending', max_length=20, verbose_name='审核状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
                'ordering': ['-created_at'],
            },
        ),
    ]
