# Generated by Django 4.2.29 on 2026-04-08 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_initial'),
        ('requirements', '0001_initial'),
        ('tests', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='计划名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '执行中'), ('completed', '已完成')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cases', models.ManyToManyField(blank=True, related_name='test_plans', to='tests.functioncase', verbose_name='测试用例')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_test_plans', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_plans', to='projects.project', verbose_name='所属项目')),
                ('requirements', models.ManyToManyField(blank=True, related_name='test_plans', to='requirements.requirement', verbose_name='关联需求')),
            ],
            options={
                'verbose_name': '测试计划',
                'verbose_name_plural': '测试计划',
                'ordering': ['-created_at'],
            },
        ),
    ]
